name: Invalidations
description: 'Evaluate number of invalidations'

inputs:
  test_script:
    description: 'Script to test for invalidations. Defaults to `using Package`'
    required: false
    default: ''

outputs:
  total: 
    description: "Total number of invalidations"
    value: ${{ steps.invs.outputs.total }}
  deps: 
    description: "Number of invalidations caused by deps"
    value: ${{ steps.invs.outputs.deps }}

runs:
  using: "composite"
  steps: 
    - name: Get package name
      id: info
      run: |
          REPONAME="${{ github.event.repository.name }}"
          PACKAGENAME=${REPONAME%.jl}
          echo "packagename=$PACKAGENAME" >> $GITHUB_OUTPUT
          if [[ '${{ inputs.test_script }}' == '' ]]; then
            TESTSCRIPT="using ${PACKAGENAME}"
          else
            TESTSCRIPT=${{ inputs.test_script }}
          fi
          echo "testscript=$TESTSCRIPT" >> $GITHUB_OUTPUT
          if [[ '${{ inputs.setup_script }}' == '' ]]; then
            SETUPSCRIPT="using Pkg;Pkg.develop(\"${PACKAGENAME}\")"
          else
            SETUPSCRIPT=${{ inputs.setup_script }}
          fi
          echo "setupscript=$SETUPSCRIPT" >> $GITHUB_OUTPUT
      shell: bash
      
    - name: Install SnoopCompile tools
      run: julia 'using Pkg; Pkg.add(["SnoopCompileCore", "SnoopCompile", "PrettyTables"])'
      shell: bash
    - name: Load package on branch
      id: invs
      run: |
        ${{ steps.info.outputs.setupscript }}
        using SnoopCompileCore
        invalidations = @snoopr begin ${{ steps.info.outputs.testscript }} end
        
        using SnoopCompile
        inv_owned = length(filtermod(${{ steps.info.outputs.packagename }}, invalidation_trees(invalidations)))
        inv_total = length(uinvalidated(invalidations))
        inv_deps = inv_total - inv_owned
        
        @show inv_total, inv_deps

        # Report invalidations summary:
        using PrettyTables  # needed for `report_invalidations` to be defined
        SnoopCompile.report_invalidations(;
             invalidations,
             process_filename = x -> last(split(x, ".julia/packages/")),
             n_rows = 0,  # no-limit (show all invalidations)
        )

        # Set outputs
        open(ENV["GITHUB_OUTPUT"], "a") do io
          println(io, "total=$(inv_total)")
          println(io, "deps=$(inv_deps)")
        end
      shell: julia --color=yes {0}    
